[package]
name = "template"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "template.rs"

[dependencies]
xp_crate = { path = "../../" }
serde = { version = "1", features = ["derive"] }
